//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Du_an__1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int AdminID { get; set; }
        public string AdminName { get; set; }
        public string AUserName { get; set; }
        public string AEmail { get; set; }
        public string APhone { get; set; }
        public string APassword { get; set; }
    }
}
